### ISSUE TITLE
_cp_file() got an unexpected keyword argument 'maxdepth'

### ISSUE THREAD

**Issue by majidaldo** [intake/filesystem_spec#505]
fsspec ver = 0.8.5

` _cp_file() got an unexpected keyword argument 'maxdepth'` triggered from `fs.mv`.

works fine in 0.8.4.

**Comment by martindurant** [comment]
Please let us know the operation you were trying to do, the exact call you made.

**Comment by majidaldo** [comment]
just a plain `fs.mv(src, dst)`.

**Comment by martindurant** [comment]
What is `fs`?

**Comment by majidaldo** [comment]
instantiated fssspec

**Comment by martindurant** [comment]
*please* show me code! Fsspec is not a class, it contains many classes. What exactly did you do?

On December 20, 2020 2:04:35 PM EST, Majid alDosari <notifications@github.com> wrote:
>instantiated fssspec
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/intake/filesystem_spec/issues/505#issuecomment-748647368

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by majidaldo** [comment]
It's essentially this.
```
fs = fsspec.filesystem('az', **secrets)
fs.mv(src, dst)
```

**Comment by martindurant** [comment]
Thank you for specifying that this was azure, and that you were calling `mv` with `recursive=False`. These are critical details. It would also have been useful to know your version of `adlfs`
Before investigating further, a new version of adlfs is available on pypi and conda: 0.5.9. There is a good chance it solves the problem, so please try upgrading.

**Comment by majidaldo** [comment]
Thanks! I updated adlfs, but unfortunately, the issue remains.

**Comment by majidaldo** [comment]
resolved new with latest updates
